-- Add extended metadata columns to shows table
ALTER TABLE public.shows 
ADD COLUMN IF NOT EXISTS event_name text,
ADD COLUMN IF NOT EXISTS venue text,
ADD COLUMN IF NOT EXISTS room_name text,
ADD COLUMN IF NOT EXISTS event_start_date date,
ADD COLUMN IF NOT EXISTS event_end_date date,
ADD COLUMN IF NOT EXISTS call_time time,
ADD COLUMN IF NOT EXISTS doors_time time,
ADD COLUMN IF NOT EXISTS show_time time,
ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'America/Los_Angeles',
ADD COLUMN IF NOT EXISTS logo_url text,
ADD COLUMN IF NOT EXISTS brand_color text DEFAULT '#6E59A5',
ADD COLUMN IF NOT EXISTS secondary_color text DEFAULT '#38B2AC',
ADD COLUMN IF NOT EXISTS apply_branding boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS timecode_format text DEFAULT '30fps',
ADD COLUMN IF NOT EXISTS default_tracks text[] DEFAULT ARRAY['audio', 'video', 'lighting', 'stage']::text[],
ADD COLUMN IF NOT EXISTS autosave_interval integer DEFAULT 30,
ADD COLUMN IF NOT EXISTS show_template text DEFAULT 'general',
ADD COLUMN IF NOT EXISTS rehearsal_mode boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS locked boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS audio_latency_offset integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_latency_offset integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS safety_mode boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS team_show_caller text,
ADD COLUMN IF NOT EXISTS team_technical_director text,
ADD COLUMN IF NOT EXISTS team_producer text,
ADD COLUMN IF NOT EXISTS team_stage_manager text,
ADD COLUMN IF NOT EXISTS team_lighting_lead text,
ADD COLUMN IF NOT EXISTS team_audio_lead text,
ADD COLUMN IF NOT EXISTS team_video_lead text;